apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.component }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-{{ .Values.component }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
      {{- if .Values.ports.nodeHttpPort }}
      nodePort: {{ .Values.ports.nodeHttpPort }}
      {{- end }}
    {{- if eq .Values.component "optuna" }}
    - name: grpc
      protocol: TCP
      port: {{ .Values.ports.grpc }}
      targetPort: {{ .Values.ports.grpc }}
      {{- if .Values.ports.nodeGrpcPort }}
      nodePort: {{ .Values.ports.nodeGrpcPort }}
      {{- end }}
    {{- end }}
