# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metric.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "metric.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cmetric.proto\x12\x06metric"q\n\rMetricRequest\x12\x0e\n\x06prj_id\x18\x01 \x01(\t\x12\x15\n\rexperiment_id\x18\x02 \x01(\t\x12\x10\n\x08run_uuid\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\x0b\n\x03\x64im\x18\x05 \x01(\x05\x12\r\n\x05value\x18\x06 \x01(\x0c" \n\x0eMetricResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8c\x01\n\rMetricService\x12;\n\nSendMetric\x12\x15.metric.MetricRequest\x1a\x16.metric.MetricResponse\x12>\n\x0bSendMetrics\x12\x15.metric.MetricRequest\x1a\x16.metric.MetricResponse(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "metric_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_METRICREQUEST"]._serialized_start = 24
    _globals["_METRICREQUEST"]._serialized_end = 137
    _globals["_METRICRESPONSE"]._serialized_start = 139
    _globals["_METRICRESPONSE"]._serialized_end = 171
    _globals["_METRICSERVICE"]._serialized_start = 174
    _globals["_METRICSERVICE"]._serialized_end = 314
# @@protoc_insertion_point(module_scope)
