apiVersion: v1
kind: Secret
metadata:
  name: chain-secret
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
