---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chain-server-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chain-server-role
  namespace: default
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["pods", "deployments", "jobs", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chain-server-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: chain-server-sa
    namespace: default
roleRef:
  kind: Role
  name: chain-server-role
  apiGroup: rbac.authorization.k8s.io
