apiVersion: v1
kind: Service
metadata:
  name: chain-server
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  selector:
    app: chain-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8180
    - protocol: TCP
      port: 8050
      targetPort: 8050
