FROM python:3.12-slim
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Tokyo
WORKDIR /app
RUN pip install --no-cache-dir optuna optuna-dashboard gunicorn pymysql cryptography boto3 plotly grpcio protobuf
# chain sever コンテナ基準
COPY ./app .
EXPOSE 8000
CMD ["gunicorn", "app:app", "--workers", "1", "-b", "0.0.0.0:8000"]
